### ISSUE TITLE
Display tweaks II (Pictoralist)

### ISSUE THREAD

**Issue by icejag** [Display-Lab/precision-feedback-pipeline#136]
- For Pilot Display only 6 months of data in pictoralist for both bar graphs and line chart

**Comment by zachll** [comment]
- change background color to match blue of email template (test this - maybe change to a different color, or we may determine that charts need to have a white background)
 - Change chart size to 500 x 250 or slightly larger, and adjust font sizes accordingly
 - Change font color to white for performance data appearing within bars of bar chart
 - Improve the contrast of the goal line for bar charts, when compared to the chart background and bar colors
 - add dots/points to lines of line graphs, so that missing data are more clearly missing
 - consider removing dashed line in line graphs if the addition of points makes missing data more easily understood and looks OK
 - Propose a solution for handling missing data in the first month of a line chart, as there will be no point to connect a dashed line to. Does the addition of points satisfy this?

**Comment by icejag** [comment]
@zachll Mark wanted the background color as transparent.

**Comment by mackgalante** [comment]
Minor changes:

- [ ] Background transparency
- [ ] Chart final resolution
- [ ] Font color changes
- [ ] Goal line coloration

Intermediate changes:

- [ ] Remove ghost_frame code for dashed line plotting, revert to plotting gaps with data points

Major changes:

- [ ] Using datetime to determine current month and plot gap data point in most recent month if no data exists 
- Better solution probably to stop candidate selection entirely if measure lacks data for the month the feedback is being generated about

**Comment by mackgalante** [comment]
Need specific hexadecimal colors if the ones from the prototype slides are not correct, current colors are sampled from that slide deck

**Comment by mackgalante** [comment]
![response_2023-11-09 16:13:40 401660](https://github.com/Display-Lab/precision-feedback-pipeline/assets/133153871/fba2e72e-4d69-48f7-8205-322c3ca8448f)

Bar chart with gaps and latest tweaks

**Comment by mackgalante** [comment]
![response_2023-11-09 16:15:32 266246](https://github.com/Display-Lab/precision-feedback-pipeline/assets/133153871/156e8a24-ca4e-460c-a4ff-b897116d5e00)

Line chart with gaps and latest tweaks

**Comment by mackgalante** [comment]
Goal lines now chart in black, and only are drawn when the comparator_type is not goal, that way there isn't redundancies (thus why no goal lines are plotted above)

**Comment by zachll** [comment]
Seeing the new dimensions, I'm suspecting that 500x250 is for the entire widget (text + chart), so we should confirm that asap, I will email now

**Comment by zachll** [comment]
Based on these examples we are really close. I think the remaining issues from #132 

- [ ] limit precision of recipient performance in bar and line charts to zero decimal points (i.e. 89% instead of 89.0%)
- [ ] add case count values for numerator and denominator to recipient performance in bar and line charts (all months of recipient bars, but only last three months of line chart) - looks like this is done for bar chart but not line chart
- [ ] remove chart labels above bar chart and line chart
- [ ] remove axis labels "Performance Level" and "Time" from charts
- [ ] Rotate month labels on x axis to be horizontal
- [ ] change legend to display items in one row, horizontally, rather than a column or chart inset
- [ ] remove border around legend
- [ ] increase font sizes by 3 to 5 points or so

**Comment by zachll** [comment]
- [ ] display of the goal line should be limited only to bar charts, not the line chart
