### ISSUE TITLE
gap annotations have negative size for positive gaps

### ISSUE THREAD

**Issue by faridseifi** [Display-Lab/precision-feedback-pipeline#271]
## problem
We are reporting the candidate list in debug mode and esteemer 2 is using gap size as score so we noticed that messages about positive gaps like "social better" have a negative score/gap size.

Use the following test case to replicate this issue with esteemer 2 set to true or look at the gap size in the output of bitstomach:
 [7,"SUS04","2023-12-01",92,10,100,85,89,91,90]

output message:
    "candidates": [
        {
            "score": -1.0,
            "measure": "SUS04",
            "name": "Congratulations High Performance",
            "acceptable_by": [
                "Social better"
            ],
            "selected": "true"
        },
         ...
     ]

bitstomach output:
...
{
        "@id": "_:N4e24cd6044224e9597ff4aaa3fcf4a25",
        "@type": [
            "http://purl.obolibrary.org/obo/PSDO_0000104"
        ],
        "http://example.com/slowmo#PerformanceGapSize": [
            {
                "@value": -0.9993406593406593
            }
        ],
...

**Comment by icejag** [comment]
This is not a bug. Because the gap sizes are normalized in the range(-1 to1). Please kindly check the is[issue](https://github.com/orgs/Display-Lab/projects/1/views/1?filterQuery=Normalize&pane=issue&itemId=52080349)

**Comment by faridseifi** [comment]
Hi @icejag Ayshwarya, Thank you for your comment. I see that the normalization algorithm is applied in Bitstomach and it updates the actual gap size in the graph. We need to use the actual gap size in esteemer 2 and that causes issues.  I don't think the normalization should be the responsibility of Bitstomach, maybe it could be done in esteemer 1 where the normalized values are used. In other words, the normalized value is not the gap size anymore so even if it is implemented in Bitstomach it would help if it is added to the graph with a different key (something like NormalizedPerformanceGapSize) so that we keep the actual gap size. 

I also noticed that the normalization could generate a negative value for a positive gaps size which I thought might not make sense.

**Comment by pboisver** [comment]
We will revisit the calculation of attributes of motivational info added by annotations so that the values are pretty close to the natural scale and units (e.g. positive values for gap_size for positive gap content). We will add any additional transformation required for scoring as part of the scoring algorithm. 

No need to address this until we are using Esteemer 2.

**Comment by icejag** [comment]
@faridseifi The positivite and negative signs of the gap are shown in the annotations psdo0000104 - positive gap and psdo0000105 negative gap. The normalization works well with gap annotations because as such the esteemer's conceptual responsibility does not include normalization. I am not sure why we should have the original gap content in the performer graph.
