### ISSUE TITLE
[bug] error loading causal pathways from knowledgebase repo

### ISSUE THREAD

**Issue by icejag** [Display-Lab/precision-feedback-pipeline#89]
The error comes often. What is our back up plan for this?

<img width="1728" alt="Screenshot 2023-10-28 at 12 17 33 AM" src="https://github.com/Display-Lab/precision-feedback-pipeline/assets/48527835/c5a224ea-35d9-4608-ba7e-5509740cf0fb">

**Comment by mackgalante** [comment]
Likely related to the issue of github rate limitations, will investigate

Please provide more context on how to reproduce the bug!

**Comment by icejag** [comment]
![Image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/48527835/f03fbf67-3f5c-491b-8d16-a907ae2c5d46)

Am not able to test locally by exporting and changing the .env file.

**Comment by mackgalante** [comment]
To write down our current thinking, has everything to do with the volume of API calls on startup as we scrape the knowledgebase repo. We have strategies for handling this in production, however for local high-intensity testing where the pipeline is being reloaded over and over, local repo copies seem to be our Occam's razor here. 

I will include the main file I have been using which uses local file references in order to load the pipeline from local PFKB clones, feel free to use it!

Only caveat is the basesettings class needs to have the direct file references changed to match the individual's file path to a PFKB clone. This can be set in your .env file or directly referenced in the settings class on startup of main, as I opted to do here.

**Comment by mackgalante** [comment]
From .env:
```zsh
templates=/Users/.../Display-Lab/knowledge-base/message_templates/  
pathways=/Users/.../Display-Lab/knowledge-base/causal_pathways/  
measures=file:///Users/.../Display-Lab/knowledge-base/measures.json  
mpm=file:///Users/mack/Code/Display-Lab/knowledge-base/motivational_potential_model.csv  
pictoraless="false" 
```
